# Generated by Django 2.0.13 on 2019-03-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmailaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('verified', models.IntegerField()),
                ('primary', models.IntegerField()),
            ],
            options={
                'db_table': 'account_emailaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmailconfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'account_emailconfirmation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=191)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.TextField()),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('client_id', models.CharField(max_length=191)),
                ('secret', models.CharField(max_length=191)),
                ('key', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'socialaccount_socialapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialappSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'socialaccount_socialapp_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('token_secret', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socialaccount_socialtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'users_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'users_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp2Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_2_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp2Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_2_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp2Taxonomyfield',
            fields=[
                ('field_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_label', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, max_length=255, null=True)),
                ('field_desc', models.TextField(blank=True, null=True)),
                ('field_val', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_2_taxonomyfield',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp2Taxonomymeta',
            fields=[
                ('meta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('taxonomy_id', models.BigIntegerField()),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_2_taxonomymeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp3Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_3_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp3Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_3_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp4Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_4_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp4Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_4_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp5Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_5_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp5Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_5_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclContentStatus',
            fields=[
                ('rid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nid', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'wp_6_icl_content_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclCoreStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField()),
                ('module', models.CharField(max_length=16)),
                ('origin', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_core_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=10, unique=True)),
                ('flag', models.CharField(max_length=32)),
                ('from_template', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_flags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('english_name', models.CharField(max_length=128, unique=True)),
                ('major', models.IntegerField()),
                ('active', models.IntegerField()),
                ('default_locale', models.CharField(blank=True, max_length=35, null=True)),
                ('tag', models.CharField(blank=True, max_length=35, null=True)),
                ('encode_url', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclLanguagesTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=7)),
                ('display_language_code', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wp_6_icl_languages_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclLocaleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('locale', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'wp_6_icl_locale_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclMessageStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField(unique=True)),
                ('object_id', models.BigIntegerField()),
                ('from_language', models.CharField(max_length=10)),
                ('to_language', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
                ('object_type', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_message_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclNode',
            fields=[
                ('nid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('md5', models.CharField(max_length=32)),
                ('links_fixed', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclReminders',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('url', models.TextField()),
                ('can_delete', models.IntegerField()),
                ('show', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclStringPositions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('string_id', models.BigIntegerField()),
                ('kind', models.IntegerField(blank=True, null=True)),
                ('position_in_page', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wp_6_icl_string_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclStrings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=7)),
                ('context', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('value', models.TextField()),
                ('string_package_id', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.IntegerField()),
                ('gettext_context', models.TextField()),
                ('domain_name_context_md5', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'wp_6_icl_strings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclStringStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField()),
                ('string_translation_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'wp_6_icl_string_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclStringTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('string_id', models.BigIntegerField()),
                ('language', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('value', models.TextField(blank=True, null=True)),
                ('translator_id', models.BigIntegerField(blank=True, null=True)),
                ('translation_service', models.CharField(max_length=16)),
                ('batch_id', models.IntegerField()),
                ('translation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_6_icl_string_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclTranslate',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.BigIntegerField()),
                ('content_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('field_type', models.CharField(max_length=160)),
                ('field_format', models.CharField(max_length=16)),
                ('field_translate', models.IntegerField()),
                ('field_data', models.TextField()),
                ('field_data_translated', models.TextField()),
                ('field_finished', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_6_icl_translate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclTranslateJob',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField()),
                ('translator_id', models.PositiveIntegerField()),
                ('translated', models.PositiveIntegerField()),
                ('manager_id', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_6_icl_translate_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclTranslationBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.TextField()),
                ('tp_id', models.IntegerField(blank=True, null=True)),
                ('ts_url', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_6_icl_translation_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclTranslations',
            fields=[
                ('translation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=36)),
                ('element_id', models.BigIntegerField(blank=True, null=True)),
                ('trid', models.BigIntegerField()),
                ('language_code', models.CharField(max_length=7)),
                ('source_language_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'wp_6_icl_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6IclTranslationStatus',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('translation_id', models.BigIntegerField(unique=True)),
                ('status', models.IntegerField()),
                ('translator_id', models.BigIntegerField()),
                ('needs_update', models.IntegerField()),
                ('md5', models.CharField(max_length=32)),
                ('translation_service', models.CharField(max_length=16)),
                ('batch_id', models.IntegerField()),
                ('translation_package', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('links_fixed', models.IntegerField()),
                ('field_prevstate', models.TextField(blank=True, db_column='_prevstate', null=True)),
            ],
            options={
                'db_table': 'wp_6_icl_translation_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_6_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_6_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp6WpRpTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('post_date', models.DateTimeField()),
                ('label', models.CharField(max_length=32)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_6_wp_rp_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp7Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_7_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp7Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_7_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp8Popularpostsdata',
            fields=[
                ('postid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('pageviews', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_8_popularpostsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wp8Popularpostssummary',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('postid', models.BigIntegerField()),
                ('pageviews', models.BigIntegerField()),
                ('view_date', models.DateField()),
                ('last_viewed', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_8_popularpostssummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpBlogs',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_id', models.BigIntegerField()),
                ('domain', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=100)),
                ('registered', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('public', models.IntegerField()),
                ('archived', models.IntegerField()),
                ('mature', models.IntegerField()),
                ('spam', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('lang_id', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_blogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpBlogVersions',
            fields=[
                ('blog_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('db_version', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_blog_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpCommentmeta',
            fields=[
                ('meta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_id', models.BigIntegerField()),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_commentmeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpComments',
            fields=[
                ('comment_id', models.BigAutoField(db_column='comment_ID', primary_key=True, serialize=False)),
                ('comment_post_id', models.BigIntegerField(db_column='comment_post_ID')),
                ('comment_author', models.TextField()),
                ('comment_author_email', models.CharField(max_length=100)),
                ('comment_author_url', models.CharField(max_length=200)),
                ('comment_author_ip', models.CharField(db_column='comment_author_IP', max_length=100)),
                ('comment_date', models.DateTimeField()),
                ('comment_date_gmt', models.DateTimeField()),
                ('comment_content', models.TextField()),
                ('comment_karma', models.IntegerField()),
                ('comment_approved', models.CharField(max_length=20)),
                ('comment_agent', models.CharField(max_length=255)),
                ('comment_type', models.CharField(max_length=20)),
                ('comment_parent', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'wp_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpDomainMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_id', models.BigIntegerField()),
                ('domain', models.CharField(max_length=255)),
                ('active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_domain_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfDraftSubmissions',
            fields=[
                ('uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('form_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField()),
                ('ip', models.CharField(max_length=39)),
                ('source_url', models.TextField()),
                ('submission', models.TextField()),
            ],
            options={
                'db_table': 'wp_gf_draft_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.PositiveIntegerField()),
                ('post_id', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('is_starred', models.IntegerField()),
                ('is_read', models.IntegerField()),
                ('ip', models.CharField(max_length=39)),
                ('source_url', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=250)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_fulfilled', models.IntegerField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wp_gf_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfEntryMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_id', models.PositiveIntegerField()),
                ('entry_id', models.BigIntegerField()),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_value', models.TextField(blank=True, null=True)),
                ('item_index', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'wp_gf_entry_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfEntryNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(blank=True, max_length=250, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('value', models.TextField(blank=True, null=True)),
                ('note_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'wp_gf_entry_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField()),
                ('is_trash', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_gf_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfFormMeta',
            fields=[
                ('form_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('display_meta', models.TextField(blank=True, null=True)),
                ('entries_grid_meta', models.TextField(blank=True, null=True)),
                ('confirmations', models.TextField(blank=True, null=True)),
                ('notifications', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_gf_form_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfFormRevisions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_id', models.PositiveIntegerField()),
                ('display_meta', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_gf_form_revisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpGfFormView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField()),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'wp_gf_form_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclCmsNavCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cache_key', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('data', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_icl_cms_nav_cache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclContentStatus',
            fields=[
                ('rid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nid', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'wp_icl_content_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclCoreStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField()),
                ('module', models.CharField(max_length=16)),
                ('origin', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField()),
                ('tp_revision', models.IntegerField()),
                ('ts_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_icl_core_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=10, unique=True)),
                ('flag', models.CharField(max_length=32)),
                ('from_template', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_icl_flags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('english_name', models.CharField(max_length=128, unique=True)),
                ('major', models.IntegerField()),
                ('active', models.IntegerField()),
                ('default_locale', models.CharField(blank=True, max_length=35, null=True)),
                ('encode_url', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'wp_icl_languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclLanguagesTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=7)),
                ('display_language_code', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wp_icl_languages_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclLocaleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('locale', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'wp_icl_locale_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclMessageStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField(unique=True)),
                ('object_id', models.BigIntegerField()),
                ('from_language', models.CharField(max_length=10)),
                ('to_language', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
                ('object_type', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'wp_icl_message_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclMoFilesDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=250)),
                ('file_path_md5', models.CharField(max_length=32, unique=True)),
                ('domain', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=20)),
                ('num_of_strings', models.IntegerField()),
                ('last_modified', models.IntegerField()),
                ('component_type', models.CharField(max_length=6)),
                ('component_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'wp_icl_mo_files_domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclNode',
            fields=[
                ('nid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('md5', models.CharField(max_length=32)),
                ('links_fixed', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_icl_node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclReminders',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('url', models.TextField()),
                ('can_delete', models.IntegerField()),
                ('show', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_icl_reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStringPackages',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('kind_slug', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=160)),
                ('edit_link', models.TextField()),
                ('view_link', models.TextField()),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('word_count', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'wp_icl_string_packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStringPages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('string_id', models.BigIntegerField()),
                ('url_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'wp_icl_string_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStringPositions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('string_id', models.BigIntegerField()),
                ('kind', models.IntegerField(blank=True, null=True)),
                ('position_in_page', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wp_icl_string_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStrings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('context', models.CharField(blank=True, max_length=160, null=True)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('value', models.TextField()),
                ('string_package_id', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.IntegerField()),
                ('gettext_context', models.TextField()),
                ('domain_name_context_md5', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('location', models.BigIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('translation_priority', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'wp_icl_strings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStringStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField()),
                ('string_translation_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('md5', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'wp_icl_string_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStringTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('string_id', models.BigIntegerField()),
                ('language', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('value', models.TextField(blank=True, null=True)),
                ('mo_string', models.TextField(blank=True, null=True)),
                ('translator_id', models.BigIntegerField(blank=True, null=True)),
                ('translation_date', models.DateTimeField()),
                ('batch_id', models.IntegerField()),
                ('translation_service', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'wp_icl_string_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclStringUrls',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=7, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wp_icl_string_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclTranslate',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.BigIntegerField()),
                ('content_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('field_type', models.CharField(max_length=160)),
                ('field_format', models.CharField(max_length=16)),
                ('field_translate', models.IntegerField()),
                ('field_data', models.TextField()),
                ('field_data_translated', models.TextField()),
                ('field_finished', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_icl_translate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclTranslateJob',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.BigIntegerField()),
                ('translator_id', models.PositiveIntegerField()),
                ('translated', models.PositiveIntegerField()),
                ('manager_id', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'wp_icl_translate_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclTranslationBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.TextField()),
                ('tp_id', models.IntegerField(blank=True, null=True)),
                ('ts_url', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_icl_translation_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclTranslations',
            fields=[
                ('translation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=60)),
                ('element_id', models.BigIntegerField(blank=True, null=True)),
                ('trid', models.BigIntegerField()),
                ('language_code', models.CharField(max_length=7)),
                ('source_language_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'wp_icl_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpIclTranslationStatus',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('translation_id', models.BigIntegerField(unique=True)),
                ('status', models.IntegerField()),
                ('translator_id', models.BigIntegerField()),
                ('needs_update', models.IntegerField()),
                ('md5', models.CharField(max_length=32)),
                ('translation_service', models.CharField(max_length=16)),
                ('translation_package', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('links_fixed', models.IntegerField()),
                ('field_prevstate', models.TextField(blank=True, db_column='_prevstate', null=True)),
                ('batch_id', models.IntegerField()),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('tp_id', models.IntegerField(blank=True, null=True)),
                ('tp_revision', models.IntegerField()),
                ('ts_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_icl_translation_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpInboundEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('page_id', models.BigIntegerField()),
                ('variation_id', models.BigIntegerField()),
                ('form_id', models.BigIntegerField()),
                ('cta_id', models.BigIntegerField()),
                ('email_id', models.BigIntegerField()),
                ('rule_id', models.BigIntegerField()),
                ('job_id', models.BigIntegerField()),
                ('list_id', models.BigIntegerField()),
                ('lead_id', models.BigIntegerField()),
                ('comment_id', models.BigIntegerField()),
                ('lead_uid', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('event_details', models.TextField()),
                ('source', models.TextField()),
                ('funnel', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_inbound_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpInboundPageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.BigIntegerField()),
                ('cta_id', models.BigIntegerField()),
                ('variation_id', models.BigIntegerField()),
                ('lead_id', models.BigIntegerField()),
                ('lead_uid', models.CharField(max_length=255)),
                ('list_id', models.BigIntegerField()),
                ('session_id', models.CharField(max_length=255)),
                ('source', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('ip', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'wp_inbound_page_views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpInboundTrackedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('args', models.TextField()),
            ],
            options={
                'db_table': 'wp_inbound_tracked_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpItsecLockouts',
            fields=[
                ('lockout_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lockout_type', models.CharField(max_length=20)),
                ('lockout_start', models.DateTimeField()),
                ('lockout_start_gmt', models.DateTimeField()),
                ('lockout_expire', models.DateTimeField()),
                ('lockout_expire_gmt', models.DateTimeField()),
                ('lockout_host', models.CharField(blank=True, max_length=40, null=True)),
                ('lockout_user', models.BigIntegerField(blank=True, null=True)),
                ('lockout_username', models.CharField(blank=True, max_length=60, null=True)),
                ('lockout_active', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_itsec_lockouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpItsecLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(max_length=20)),
                ('log_function', models.CharField(max_length=255)),
                ('log_priority', models.IntegerField()),
                ('log_date', models.DateTimeField()),
                ('log_date_gmt', models.DateTimeField()),
                ('log_host', models.CharField(blank=True, max_length=40, null=True)),
                ('log_username', models.CharField(blank=True, max_length=60, null=True)),
                ('log_user', models.BigIntegerField(blank=True, null=True)),
                ('log_url', models.CharField(blank=True, max_length=255, null=True)),
                ('log_referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('log_data', models.TextField()),
            ],
            options={
                'db_table': 'wp_itsec_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpItsecTemp',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temp_type', models.CharField(max_length=20)),
                ('temp_date', models.DateTimeField()),
                ('temp_date_gmt', models.DateTimeField()),
                ('temp_host', models.CharField(blank=True, max_length=40, null=True)),
                ('temp_user', models.BigIntegerField(blank=True, null=True)),
                ('temp_username', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'wp_itsec_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpLinks',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_url', models.CharField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
                ('link_image', models.CharField(max_length=255)),
                ('link_target', models.CharField(max_length=25)),
                ('link_description', models.CharField(max_length=255)),
                ('link_visible', models.CharField(max_length=20)),
                ('link_owner', models.BigIntegerField()),
                ('link_rating', models.IntegerField()),
                ('link_updated', models.DateTimeField()),
                ('link_rel', models.CharField(max_length=255)),
                ('link_notes', models.TextField()),
                ('link_rss', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wp_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpNewsSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('timestamp', models.TextField()),
                ('estado', models.IntegerField()),
                ('lang', models.TextField()),
            ],
            options={
                'db_table': 'wp_news_subs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpNf3ActionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('key', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_nf3_action_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpNf3Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_nf3_actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpNf3Chunks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_nf3_chunks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpNf3FieldMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('key', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_nf3_field_meta',
                'managed': False,
            },
        ),
    ]
